version: "3"
services:
  target:
    build:
      context: postgres
    hostname: dbpostgres
    environment:
      - POSTGRES_USER=target
      - POSTGRES_PASSWORD=target
      - POSTGRES_DB=target
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "target" ]
      interval: 10s
      timeout: 5s
      retries: 5
  source:
    build:
      context: mysql
    hostname: dbmysql
    environment:
      - MYSQL_USER=source
      - MYSQL_PASSWORD=source
      - MYSQL_ROOT_PASSWORD=source
      - MYSQL_DATABASE=source
    ports:
      - "3308:3306"
    healthcheck:
          test: ["CMD-SHELL", 'mysql --database=source --password=source --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
          interval: 5s
          timeout: 5s
          retries: 5
    deploy:
      resources:
        reservations:
          cpus: "4.0"
          memory: 2G

  symds:
    build:
      context: symmetricds
    hostname: symmetricsds
    depends_on:
      target:
        condition: service_healthy
      source:
        condition: service_healthy
    ports:
      - "31425:31415"
      - "31427:31417"

