# general
spring:
  application:
    name: MainApp
  datasource:
    url: jdbc:postgresql://postgres-main-db/MAIN_DATABASE
    username: TestUser
    driver-class-name: org.postgresql.Driver
    password: TestPassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
#      data-locations: classpath:import.sql
      mode: always

logging:
  level:
    org.hibernate: error
    org.springframework.cache: error
    org.springframework.security.saml2: DEBUG
