DROP TABLE IF EXISTS eq_users;

CREATE TABLE eq_users
(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    login VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    firstname VARCHAR(255),
    lastname VARCHAR(255),
    GUID CHAR(36),
    INDEX GUID_index (GUID)
);